# Nom de l'application
spring.application.name=projet-service

# Port du serveur
server.port=8082
spring.h2.console.enabled=true

# Configuration de la base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/projet-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Matching strategy pour Spring MVC
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Clé publique pour JWT (RSA)
rsa.publicKey=classpath:keys/publicKey.pem
